CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "pickup_points" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL,
  "address" text NOT NULL,
  "registered_at" timestamp DEFAULT (now())
);

CREATE TABLE "receivings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pickup_point_id" integer NOT NULL,
  "started_at" timestamp DEFAULT (now()),
  "closed_at" timestamp,
  "status" varchar(20) NOT NULL DEFAULT 'in_progress'
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "receiving_id" integer NOT NULL,
  "added_at" timestamp DEFAULT (now()),
  "type" varchar(50) NOT NULL,
  "description" text,
  "avito_order_id" varchar(100) NOT NULL
);

CREATE TABLE "tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL
);

CREATE INDEX "idx_users_email" ON "users" ("email");

CREATE INDEX "idx_users_role" ON "users" ("role");

CREATE INDEX "idx_pickup_points_city" ON "pickup_points" ("city");

CREATE INDEX "idx_receivings_pickup_point_id" ON "receivings" ("pickup_point_id");

CREATE INDEX "idx_receivings_status" ON "receivings" ("status");

CREATE INDEX "idx_receivings_started_at" ON "receivings" ("started_at");

CREATE INDEX "idx_receivings_pickup_status" ON "receivings" ("pickup_point_id", "status");

CREATE INDEX "idx_products_receiving_id" ON "products" ("receiving_id");

CREATE INDEX "idx_products_added_at" ON "products" ("added_at");

CREATE INDEX "idx_products_type" ON "products" ("type");

CREATE INDEX "idx_tokens_token" ON "tokens" ("token");

CREATE INDEX "idx_tokens_user_id" ON "tokens" ("user_id");

CREATE INDEX "idx_tokens_expires_at" ON "tokens" ("expires_at");

COMMENT ON COLUMN "users"."role" IS 'client, moderator, employee';

COMMENT ON COLUMN "pickup_points"."city" IS 'Москва, Санкт-Петербург, Казань';

COMMENT ON COLUMN "receivings"."status" IS 'in_progress, closed';

COMMENT ON COLUMN "products"."type" IS 'electronics, clothing, shoes';

ALTER TABLE "receivings" ADD FOREIGN KEY ("pickup_point_id") REFERENCES "pickup_points" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("receiving_id") REFERENCES "receivings" ("id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
