// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type PickupPoint struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	// Москва, Санкт-Петербург, Казань
	City         string       `json:"city"`
	Address      string       `json:"address"`
	RegisteredAt sql.NullTime `json:"registered_at"`
}

type Product struct {
	ID          int32        `json:"id"`
	ReceivingID int32        `json:"receiving_id"`
	AddedAt     sql.NullTime `json:"added_at"`
	// electronics, clothing, shoes
	Type         string         `json:"type"`
	Description  sql.NullString `json:"description"`
	AvitoOrderID string         `json:"avito_order_id"`
}

type Receiving struct {
	ID            int32        `json:"id"`
	PickupPointID int32        `json:"pickup_point_id"`
	StartedAt     sql.NullTime `json:"started_at"`
	ClosedAt      sql.NullTime `json:"closed_at"`
	// in_progress, closed
	Status string `json:"status"`
}

type Token struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type User struct {
	ID           int32  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	// client, moderator, employee
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}
